language: python
python: 3.8
branches: master

install:
  - pip install mkdocs-material
  - pip install mike

script:
  - mike install-extras

deploy:
  provider: script
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: site
  script: mike deploy ${TRAVIS_BRANCH#'release/'}
  on:
    branch: ${TRAVIS_BRANCH#'release/'}


