language: python
python: 3.8
branches: master

install:
  - pip install mkdocs-material
  - pip install mike

script:
  - mike install-extras
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - mike deploy $TRAVIS_PULL_REQUEST_BRANCH latest

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: site
  on:
    branch: master

